apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: mgu-keda
  labels:
    app: postgres
data:
  POSTGRES_DB: keda
  POSTGRES_USER: keda

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: mgu-keda
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mgu-keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.4-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-configmap
          volumeMounts:
            - name: postgres-database-storage
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgres-database-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mgu-keda
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
# dns name is db.<namespace>.svc
# no internal cluster ip address because service not exposed to internet
