
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mgu-keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: mgu-keda/api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mgu-keda
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: biz-batch
  namespace: mgu-keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biz-batch
  template:
    metadata:
      labels:
        app: biz-batch
    spec:
      containers:
        - name: biz-batch
          image: mgu-keda/batch
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD